# Generated by Django 2.1.2 on 2018-12-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
