# Generated by Django 2.1.2 on 2018-12-15 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20181215_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
