# Generated by Django 2.1.2 on 2018-12-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dm', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sp', models.CharField(max_length=200, unique=True)),
                ('don_gia', models.IntegerField()),
                ('description', models.CharField(max_length=600)),
                ('hinh', models.ImageField(upload_to='images/')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Categories')),
            ],
        ),
    ]
