# Generated by Django 2.1.2 on 2018-12-11 05:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181211_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intro',
            field=ckeditor.fields.RichTextField(default='intro text', max_length=600),
        ),
    ]
