# Generated by Django 2.1.2 on 2018-12-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=100)),
                ('mat_khau', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
